import { test } from "@playwright/test";

/**
 * The cultures the Blazor edition ships, with the resource texts the specs assert on. The values mirror the en-US and
 * da-DK resources in application/shared-kernel/SharedKernel.Localization; error messages returned by the account API are
 * not in this map because they are shown in English, as returned, in every culture.
 */
export const blazorCultures = [
  {
    locale: "en-US",
    hiWelcomeBack: "Hi! Welcome back",
    createYourAccount: "Create your account",
    enterYourVerificationCode: "Enter your verification code",
    emailAddressRequired: "Email address required",
    emailAddressTooLong: "The email address can be at most 100 characters.",
    verificationCodeFormat: "The verification code must be 6 letters.",
    validForPrefix: "Your verification code is valid for ",
    requestNewCode: "Request a new code",
    newCodeSent: "A new verification code has been sent to your email.",
    setUpYourAccount: "Let's set up your account",
    setUpYourProfile: "Let's set up your profile",
    tenantNameLength: "Name must be between 1 and 30 characters.",
    firstNameLength: "First name must be between 1 and 30 characters.",
    lastNameLength: "Last name must be between 1 and 30 characters.",
    titleTooLong: "Title must be no longer than 50 characters.",
    yourWorkspace: "Your workspace",
    logOut: "Log out",
    userMenu: "User menu",
    logoutFailed: "Logging out failed. You are still logged in, so try again.",
    logoutUnconfirmed: "We could not confirm that you were logged out, and this browser may still be logged in. Check your connection and try again.",
    logInWithEmail: "Log in with email",
    signUpWithEmail: "Sign up with email",
    verify: "Verify",
    continue: "Continue",
    users: "Users",
    search: "Search",
    userActions: "User actions",
    viewProfile: "View profile",
    changeRole: "Change role",
    changeUserRole: "Change user role",
    changeUserRoleFor: "Change user role for ",
    owner: "Owner",
    admin: "Admin",
    member: "Member",
    saveChanges: "Save changes",
    cancel: "Cancel",
    unsavedChanges: "Unsaved changes",
    stay: "Stay",
    leave: "Leave",
    userRoleUpdatedFor: "User role updated successfully for ",
    userProfile: "User profile",
    closeUserProfile: "Close user profile",
    cannotChangeOwnRole: "You cannot change your own role",
    onlyOwnersCanChangeRoles: "Only owners can change user roles",
    userNotInCurrentView: "User not in current view",
    userNotFound: "User not found",
    noUsersFound: "No users found",
    profile: "Profile",
    profileUpdated: "Profile updated successfully",
    switchAccount: "Switch account",
    sessionEnded: "Session ended",
    sessionRevoked: "Your session was ended from another device.",
    logInAgainToContinue: "Please log in again to continue.",
    logIn: "Log in",
    email: "Email",
    loginVerificationCode: "Login verification code",
    signupVerificationCode: "Signup verification code",
    signupExpired: "The signup has expired. Start again.",
    welcome: "Welcome",
    landingText: "A server-rendered public page. No WebAssembly runtime is downloaded here.",
    landingComponentText: "Rendered by the host with a FluentUI component",
    home: "Home",
    signUp: "Sign up",
    terms: "Terms",
    openTheApp: "Open the app",
    accountName: "Account name",
    firstName: "First name",
    lastName: "Last name",
    title: "Title",
    workspace: "Workspace",
    reloadBootstrap: "Reload bootstrap",
    interactiveTrue: "Interactive: True",
    notifications: "Notifications",
    dismissNotification: "Dismiss notification",
    somethingWentWrong: "Something went wrong",
    nextPage: "Next page",
    nameColumn: "Name",
    emailColumn: "Email",
    createdColumn: "Created",
    lastSeenColumn: "Last seen",
    roleColumn: "Role",
    mainNavigation: "Main navigation",
    toggleSidebar: "Toggle sidebar",
    openNavigationMenu: "Open navigation menu",
    mobileNavigationMenu: "Mobile navigation menu",
    closeMenu: "Close menu",
    changeTheme: "Change theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    pageNotFound: "Page not found",
    goToHome: "Go to home",
    showDetails: "Show details",
    hideDetails: "Hide details",
    tryAgain: "Try again"
  },
  {
    locale: "da-DK",
    hiWelcomeBack: "Hej! Velkommen tilbage",
    createYourAccount: "Opret din konto",
    enterYourVerificationCode: "Indtast din bekræftelseskode",
    emailAddressRequired: "E-mailadresse påkrævet",
    emailAddressTooLong: "E-mailadressen må højst være på 100 tegn.",
    verificationCodeFormat: "Bekræftelseskoden skal bestå af 6 bogstaver.",
    validForPrefix: "Din bekræftelseskode er gyldig i ",
    requestNewCode: "Anmod om en ny kode",
    newCodeSent: "En ny bekræftelseskode er blevet sendt til din e-mail.",
    setUpYourAccount: "Lad os opsætte din konto",
    setUpYourProfile: "Lad os opsætte din profil",
    tenantNameLength: "Navnet skal være mellem 1 og 30 tegn.",
    firstNameLength: "Fornavnet skal være mellem 1 og 30 tegn.",
    lastNameLength: "Efternavnet skal være mellem 1 og 30 tegn.",
    titleTooLong: "Titlen må højst være på 50 tegn.",
    yourWorkspace: "Dit arbejdsområde",
    logOut: "Log ud",
    userMenu: "Brugermenu",
    logoutFailed: "Log ud mislykkedes. Du er stadig logget ind, så prøv igen.",
    logoutUnconfirmed: "Vi kunne ikke bekræfte, at du blev logget ud, og denne browser kan stadig være logget ind. Tjek din forbindelse, og prøv igen.",
    logInWithEmail: "Log ind med e-mail",
    signUpWithEmail: "Tilmeld dig med e-mail",
    verify: "Bekræft",
    continue: "Fortsæt",
    users: "Brugere",
    search: "Søg",
    userActions: "Brugerhandlinger",
    viewProfile: "Se profil",
    changeRole: "Skift rolle",
    changeUserRole: "Skift brugerrolle",
    changeUserRoleFor: "Skift brugerrolle for ",
    owner: "Ejer",
    admin: "Admin",
    member: "Medlem",
    saveChanges: "Gem ændringer",
    cancel: "Annuller",
    unsavedChanges: "Ugemte ændringer",
    stay: "Bliv",
    leave: "Forlad",
    userRoleUpdatedFor: "Brugerrolle opdateret succesfuldt for ",
    userProfile: "Brugerprofil",
    closeUserProfile: "Luk brugerprofil",
    cannotChangeOwnRole: "Du kan ikke ændre din egen rolle",
    onlyOwnersCanChangeRoles: "Kun ejere kan ændre brugerroller",
    userNotInCurrentView: "Bruger ikke i nuværende visning",
    userNotFound: "Brugeren blev ikke fundet",
    noUsersFound: "Ingen brugere fundet",
    profile: "Profil",
    profileUpdated: "Profil opdateret succesfuldt",
    switchAccount: "Skift konto",
    sessionEnded: "Session afsluttet",
    sessionRevoked: "Din session blev afsluttet fra en anden enhed.",
    logInAgainToContinue: "Log venligst ind igen for at fortsætte.",
    logIn: "Log ind",
    email: "E-mail",
    loginVerificationCode: "Login-bekræftelseskode",
    signupVerificationCode: "Tilmeldingsbekræftelseskode",
    signupExpired: "Tilmeldingen er udløbet. Start forfra.",
    welcome: "Velkommen",
    landingText: "En serverrenderet offentlig side. Her hentes ingen WebAssembly-runtime.",
    landingComponentText: "Renderet af værten med en FluentUI-komponent",
    home: "Forside",
    signUp: "Tilmeld dig",
    terms: "Vilkår",
    openTheApp: "Åbn appen",
    accountName: "Kontonavn",
    firstName: "Fornavn",
    lastName: "Efternavn",
    title: "Titel",
    workspace: "Arbejdsområde",
    reloadBootstrap: "Genindlæs opstartsdata",
    interactiveTrue: "Interaktiv: True",
    notifications: "Notifikationer",
    dismissNotification: "Luk notifikationen",
    somethingWentWrong: "Noget gik galt",
    nextPage: "Næste side",
    nameColumn: "Navn",
    emailColumn: "E-mail",
    createdColumn: "Oprettet",
    lastSeenColumn: "Sidst set",
    roleColumn: "Rolle",
    mainNavigation: "Hovednavigation",
    toggleSidebar: "Skift sidepanel",
    openNavigationMenu: "Åbn navigationsmenu",
    mobileNavigationMenu: "Mobilnavigationsmenu",
    closeMenu: "Luk menu",
    changeTheme: "Skift tema",
    themeSystem: "System",
    themeLight: "Lys",
    themeDark: "Mørk",
    pageNotFound: "Siden blev ikke fundet",
    goToHome: "Gå til forsiden",
    showDetails: "Vis detaljer",
    hideDetails: "Skjul detaljer",
    tryAgain: "Prøv igen"
  }
] as const;

export type BlazorCulture = (typeof blazorCultures)[number];

/**
 * The locales of the culture projects in blazor/tests/playwright.config.ts. Every project sets its locale explicitly:
 * headless Chromium in the container otherwise reports "en-US@posix", which the .NET WebAssembly runtime rejects.
 */
export const blazorLocales: string[] = blazorCultures.map((culture) => culture.locale);

/**
 * The locale of the culture project the running test belongs to, for browser contexts a test opens itself
 */
export function blazorLocale(): string {
  return blazorTexts().locale;
}

/**
 * The text map of the culture project the running test belongs to
 */
export function blazorTexts(): BlazorCulture {
  const locale = test.info().project.use.locale;
  const culture = blazorCultures.find((candidate) => candidate.locale === locale);
  if (!culture) throw new Error(`The project "${test.info().project.name}" has no Blazor culture; its locale is "${locale}".`);
  return culture;
}

/**
 * Messages the account API returns; the Blazor pages show them as returned, in English, in every culture
 */
export const accountApiMessages = {
  wrongCode: "The code is wrong or no longer valid.",
  tooManyAttempts: "Too many attempts, please request a new code.",
  cannotChangeOwnUserRole: "You cannot change your own user role.",
  onlyOwnersCanChangeUserRoles: "Only owners are allowed to change the user roles of users.",
  userNotFound: (userId: string) => `User with id '${userId}' not found.`
} as const;
