import { test } from "@playwright/test";

/**
 * The cultures the Blazor edition ships, with the resource texts the specs assert on. The values mirror the en-US and
 * da-DK resources in application/shared-kernel/SharedKernel.Localization, and the mail texts mirror the en-US and da-DK
 * catalogs of the account's email templates in application/account/WebApp/emails/translations; error messages returned by
 * the account API are not in this map because they are shown in English, as returned, in every culture.
 */
export const blazorCultures = [
  {
    locale: "en-US",
    hiWelcomeBack: "Hi! Welcome back",
    createYourAccount: "Create your account",
    enterYourVerificationCode: "Enter your verification code",
    emailAddressRequired: "Email address required",
    emailAddressTooLong: "The email address can be at most 100 characters.",
    verificationCodeFormat: "The verification code must be 6 letters.",
    validForPrefix: "Your verification code is valid for ",
    requestNewCode: "Request a new code",
    newCodeSent: "A new verification code has been sent to your email.",
    setUpYourAccount: "Let's set up your account",
    setUpYourProfile: "Let's set up your profile",
    tenantNameLength: "Name must be between 1 and 30 characters.",
    firstNameLength: "First name must be between 1 and 30 characters.",
    lastNameLength: "Last name must be between 1 and 30 characters.",
    titleTooLong: "Title must be no longer than 50 characters.",
    yourWorkspace: "Your workspace",
    logOut: "Log out",
    userMenu: "User menu",
    logoutFailed: "Logging out failed. You are still logged in, so try again.",
    logoutUnconfirmed: "We could not confirm that you were logged out, and this browser may still be logged in. Check your connection and try again.",
    logInWithEmail: "Log in with email",
    signUpWithEmail: "Sign up with email",
    verify: "Verify",
    continue: "Continue",
    users: "Users",
    search: "Search",
    userActions: "User actions",
    viewProfile: "View profile",
    changeRole: "Change role",
    changeUserRole: "Change user role",
    changeUserRoleFor: "Change user role for ",
    owner: "Owner",
    admin: "Admin",
    member: "Member",
    saveChanges: "Save changes",
    cancel: "Cancel",
    unsavedChanges: "Unsaved changes",
    stay: "Stay",
    leave: "Leave",
    userRoleUpdatedFor: "User role updated successfully for ",
    userProfile: "User profile",
    closeUserProfile: "Close user profile",
    cannotChangeOwnRole: "You cannot change your own role",
    onlyOwnersCanChangeRoles: "Only owners can change user roles",
    userNotInCurrentView: "User not in current view",
    userNotFound: "User not found",
    noUsersFound: "No users found",
    profile: "Profile",
    profileUpdated: "Profile updated successfully",
    switchAccount: "Switch account",
    sessionEnded: "Session ended",
    sessionRevoked: "Your session was ended from another device.",
    logInAgainToContinue: "Please log in again to continue.",
    logIn: "Log in",
    email: "Email",
    loginVerificationCode: "Login verification code",
    signupVerificationCode: "Signup verification code",
    signupExpired: "The signup has expired. Start again.",
    welcome: "Welcome",
    landingText: "A server-rendered public page. No WebAssembly runtime is downloaded here.",
    landingComponentText: "Rendered by the host with a FluentUI component",
    home: "Home",
    signUp: "Sign up",
    terms: "Terms",
    openTheApp: "Open the app",
    accountName: "Account name",
    firstName: "First name",
    lastName: "Last name",
    title: "Title",
    workspace: "Workspace",
    reloadBootstrap: "Reload bootstrap",
    interactiveTrue: "Interactive: True",
    notifications: "Notifications",
    dismissNotification: "Dismiss notification",
    somethingWentWrong: "Something went wrong",
    nextPage: "Next page",
    nameColumn: "Name",
    emailColumn: "Email",
    createdColumn: "Created",
    lastSeenColumn: "Last seen",
    roleColumn: "Role",
    mainNavigation: "Main navigation",
    toggleSidebar: "Toggle sidebar",
    openNavigationMenu: "Open navigation menu",
    mobileNavigationMenu: "Mobile navigation menu",
    closeMenu: "Close menu",
    changeTheme: "Change theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    pageNotFound: "Page not found",
    goToHome: "Go to home",
    showDetails: "Show details",
    hideDetails: "Hide details",
    tryAgain: "Try again",
    or: "or",
    logInWithGoogle: "Log in with Google",
    logInWithMicrosoft: "Log in with Microsoft",
    signUpWithGoogle: "Sign up with Google",
    signUpWithMicrosoft: "Sign up with Microsoft",
    logOnWithMitId: "Log on with MitID",
    accessDenied: "Access denied",
    identityNotVerified: "Identity not verified",
    accountNotFound: "Account not found",
    accountAlreadyExists: "Account already exists",
    emailNotProvided: "Email address required",
    authenticationFailed: "Authentication failed",
    referenceId: "Reference ID: ",
    invalidRequest: "Invalid request",
    accountNotFoundMessage: "No account found for this email address. Please sign up to create an account.",
    accountAlreadyExistsMessage: "An account with this email already exists. Please log in instead.",
    authenticationFailedMessage: "We detected a security issue with your login attempt. Please try again.",
    accessDeniedMessage: "Authentication was cancelled or denied. Please try again if you want to continue.",
    identityNotVerifiedMessage: "This MitID has not been used to verify an account.",
    identityNotVerifiedHint: "Log in another way, then verify your identity from your profile to sign in with MitID.",
    verificationCodeExpired: "Your verification code has expired",
    verificationStateWrongCode: "The code was not accepted",
    verificationStateExpired: "The code has expired",
    verificationStateLocked: "Too many attempts",
    mailSignupSubject: "Confirm your email address",
    mailLoginSubjectAfterProductName: " login verification code",
    mailResendSubject: "Your verification code (resend)",
    mailUnknownUserSubject: "No account found",
    mailConfirmationCodeBelow: "Your confirmation code is below",
    mailEnterInBrowser: "Enter it in your open browser window. It is only valid for a few minutes.",
    mailResendExpiry: "This code will expire in a few minutes.",
    mailUnknownUserQuestion: "Is this the right email address?",
    inviteUser: "Invite user",
    sendInvite: "Send invite",
    userInvited: "User invited successfully",
    close: "Close",
    delete: "Delete",
    deleteUser: "Delete user",
    deleteUsers: "Delete users",
    deleteCountUsers: (count: number) => `Delete ${count} users`,
    userDeleted: (name: string) => `User deleted successfully: ${name}`,
    usersDeleted: (count: number) => `${count} users deleted successfully`,
    cannotDeleteYourself: "You cannot delete yourself",
    allUsers: "All users",
    recycleBin: "Recycle bin",
    userRecycleBin: "User recycle bin",
    deletedUsers: "Deleted users",
    restore: "Restore",
    restoreCountUsers: (count: number) => `Restore ${count} users`,
    userRestored: (name: string) => `User restored successfully: ${name}`,
    usersRestored: (count: number) => `${count} users restored successfully`,
    deletePermanently: "Delete permanently",
    permanentlyDeleteUser: "Permanently delete user",
    permanentlyDeleteUsers: "Permanently delete users",
    userPermanentlyDeleted: (name: string) => `User permanently deleted: ${name}`,
    usersPermanentlyDeleted: (count: number) => `${count} users permanently deleted`,
    emptyRecycleBin: "Empty recycle bin",
    recycleBinIsEmpty: "Recycle bin is empty",
    noPermissionToAccessPage: "You do not have permission to access this page.",
    showSearchFilters: "Show search filters",
    clearFilters: "Clear filters",
    filters: "Filters",
    clear: "Clear",
    ok: "OK",
    userRole: "User role",
    userStatus: "User status",
    startDate: "Start date",
    endDate: "End date",
    loadMore: "Load more",
    allRowsLoaded: "All rows loaded",
    selectAllUsers: "Select all users",
    selectRow: (label: string) => `Select ${label}`
  },
  {
    locale: "da-DK",
    hiWelcomeBack: "Hej! Velkommen tilbage",
    createYourAccount: "Opret din konto",
    enterYourVerificationCode: "Indtast din bekræftelseskode",
    emailAddressRequired: "E-mailadresse påkrævet",
    emailAddressTooLong: "E-mailadressen må højst være på 100 tegn.",
    verificationCodeFormat: "Bekræftelseskoden skal bestå af 6 bogstaver.",
    validForPrefix: "Din bekræftelseskode er gyldig i ",
    requestNewCode: "Anmod om en ny kode",
    newCodeSent: "En ny bekræftelseskode er blevet sendt til din e-mail.",
    setUpYourAccount: "Lad os opsætte din konto",
    setUpYourProfile: "Lad os opsætte din profil",
    tenantNameLength: "Navnet skal være mellem 1 og 30 tegn.",
    firstNameLength: "Fornavnet skal være mellem 1 og 30 tegn.",
    lastNameLength: "Efternavnet skal være mellem 1 og 30 tegn.",
    titleTooLong: "Titlen må højst være på 50 tegn.",
    yourWorkspace: "Dit arbejdsområde",
    logOut: "Log ud",
    userMenu: "Brugermenu",
    logoutFailed: "Log ud mislykkedes. Du er stadig logget ind, så prøv igen.",
    logoutUnconfirmed: "Vi kunne ikke bekræfte, at du blev logget ud, og denne browser kan stadig være logget ind. Tjek din forbindelse, og prøv igen.",
    logInWithEmail: "Log ind med e-mail",
    signUpWithEmail: "Tilmeld dig med e-mail",
    verify: "Bekræft",
    continue: "Fortsæt",
    users: "Brugere",
    search: "Søg",
    userActions: "Brugerhandlinger",
    viewProfile: "Se profil",
    changeRole: "Skift rolle",
    changeUserRole: "Skift brugerrolle",
    changeUserRoleFor: "Skift brugerrolle for ",
    owner: "Ejer",
    admin: "Admin",
    member: "Medlem",
    saveChanges: "Gem ændringer",
    cancel: "Annuller",
    unsavedChanges: "Ugemte ændringer",
    stay: "Bliv",
    leave: "Forlad",
    userRoleUpdatedFor: "Brugerrolle opdateret succesfuldt for ",
    userProfile: "Brugerprofil",
    closeUserProfile: "Luk brugerprofil",
    cannotChangeOwnRole: "Du kan ikke ændre din egen rolle",
    onlyOwnersCanChangeRoles: "Kun ejere kan ændre brugerroller",
    userNotInCurrentView: "Bruger ikke i nuværende visning",
    userNotFound: "Brugeren blev ikke fundet",
    noUsersFound: "Ingen brugere fundet",
    profile: "Profil",
    profileUpdated: "Profil opdateret succesfuldt",
    switchAccount: "Skift konto",
    sessionEnded: "Session afsluttet",
    sessionRevoked: "Din session blev afsluttet fra en anden enhed.",
    logInAgainToContinue: "Log venligst ind igen for at fortsætte.",
    logIn: "Log ind",
    email: "E-mail",
    loginVerificationCode: "Login-bekræftelseskode",
    signupVerificationCode: "Tilmeldingsbekræftelseskode",
    signupExpired: "Tilmeldingen er udløbet. Start forfra.",
    welcome: "Velkommen",
    landingText: "En serverrenderet offentlig side. Her hentes ingen WebAssembly-runtime.",
    landingComponentText: "Renderet af værten med en FluentUI-komponent",
    home: "Forside",
    signUp: "Tilmeld dig",
    terms: "Vilkår",
    openTheApp: "Åbn appen",
    accountName: "Kontonavn",
    firstName: "Fornavn",
    lastName: "Efternavn",
    title: "Titel",
    workspace: "Arbejdsområde",
    reloadBootstrap: "Genindlæs opstartsdata",
    interactiveTrue: "Interaktiv: True",
    notifications: "Notifikationer",
    dismissNotification: "Luk notifikationen",
    somethingWentWrong: "Noget gik galt",
    nextPage: "Næste side",
    nameColumn: "Navn",
    emailColumn: "E-mail",
    createdColumn: "Oprettet",
    lastSeenColumn: "Sidst set",
    roleColumn: "Rolle",
    mainNavigation: "Hovednavigation",
    toggleSidebar: "Skift sidepanel",
    openNavigationMenu: "Åbn navigationsmenu",
    mobileNavigationMenu: "Mobilnavigationsmenu",
    closeMenu: "Luk menu",
    changeTheme: "Skift tema",
    themeSystem: "System",
    themeLight: "Lys",
    themeDark: "Mørk",
    pageNotFound: "Siden blev ikke fundet",
    goToHome: "Gå til forsiden",
    showDetails: "Vis detaljer",
    hideDetails: "Skjul detaljer",
    tryAgain: "Prøv igen",
    or: "eller",
    logInWithGoogle: "Log ind med Google",
    logInWithMicrosoft: "Log ind med Microsoft",
    signUpWithGoogle: "Tilmeld dig med Google",
    signUpWithMicrosoft: "Tilmeld dig med Microsoft",
    logOnWithMitId: "Log ind med MitID",
    accessDenied: "Adgang nægtet",
    identityNotVerified: "Identitet ikke bekræftet",
    accountNotFound: "Konto ikke fundet",
    accountAlreadyExists: "Konto findes allerede",
    emailNotProvided: "E-mailadresse påkrævet",
    authenticationFailed: "Godkendelse mislykkedes",
    referenceId: "Reference-ID: ",
    invalidRequest: "Ugyldig anmodning",
    accountNotFoundMessage: "Ingen konto fundet for denne e-mailadresse. Tilmeld dig venligst for at oprette en konto.",
    accountAlreadyExistsMessage: "Der findes allerede en konto med denne e-mailadresse. Log ind i stedet.",
    authenticationFailedMessage: "Vi opdagede et sikkerhedsproblem med dit loginforsøg. Prøv venligst igen.",
    accessDeniedMessage: "Godkendelse blev annulleret eller afvist. Prøv venligst igen, hvis du vil fortsætte.",
    identityNotVerifiedMessage: "Dette MitID er ikke blevet brugt til at bekræfte en konto.",
    identityNotVerifiedHint: "Log ind på en anden måde, og bekræft derefter din identitet fra din profil for at kunne logge ind med MitID.",
    verificationCodeExpired: "Din bekræftelseskode er udløbet",
    verificationStateWrongCode: "Koden blev ikke godkendt",
    verificationStateExpired: "Koden er udløbet",
    verificationStateLocked: "For mange forsøg",
    mailSignupSubject: "Bekræft din e-mailadresse",
    mailLoginSubjectAfterProductName: "-bekræftelseskode til login",
    mailResendSubject: "Din bekræftelseskode (gensendt)",
    mailUnknownUserSubject: "Ingen konto fundet",
    mailConfirmationCodeBelow: "Din bekræftelseskode står herunder",
    mailEnterInBrowser: "Indtast den i dit åbne browservindue. Den er kun gyldig i få minutter.",
    mailResendExpiry: "Denne kode udløber om få minutter.",
    mailUnknownUserQuestion: "Er det den rigtige e-mailadresse?",
    inviteUser: "Inviter bruger",
    sendInvite: "Send invitation",
    userInvited: "Bruger inviteret succesfuldt",
    close: "Luk",
    delete: "Slet",
    deleteUser: "Slet bruger",
    deleteUsers: "Slet brugere",
    deleteCountUsers: (count: number) => `Slet ${count} brugere`,
    userDeleted: (name: string) => `Bruger slettet succesfuldt: ${name}`,
    usersDeleted: (count: number) => `${count} brugere slettet succesfuldt`,
    cannotDeleteYourself: "Du kan ikke slette dig selv",
    allUsers: "Alle brugere",
    recycleBin: "Papirkurv",
    userRecycleBin: "Papirkurv for brugere",
    deletedUsers: "Slettede brugere",
    restore: "Gendan",
    restoreCountUsers: (count: number) => `Gendan ${count} brugere`,
    userRestored: (name: string) => `Bruger genoprettet succesfuldt: ${name}`,
    usersRestored: (count: number) => `${count} brugere genoprettet succesfuldt`,
    deletePermanently: "Slet permanent",
    permanentlyDeleteUser: "Slet bruger permanent",
    permanentlyDeleteUsers: "Slet brugere permanent",
    userPermanentlyDeleted: (name: string) => `Bruger slettet permanent: ${name}`,
    usersPermanentlyDeleted: (count: number) => `${count} brugere slettet permanent`,
    emptyRecycleBin: "Tøm papirkurv",
    recycleBinIsEmpty: "Papirkurven er tom",
    noPermissionToAccessPage: "Du har ikke tilladelse til at tilgå denne side.",
    showSearchFilters: "Vis søgefiltre",
    clearFilters: "Ryd filtre",
    filters: "Filtre",
    clear: "Ryd",
    ok: "OK",
    userRole: "Brugerrolle",
    userStatus: "Brugerstatus",
    startDate: "Startdato",
    endDate: "Slutdato",
    loadMore: "Indlæs flere",
    allRowsLoaded: "Alle rækker er indlæst",
    selectAllUsers: "Vælg alle brugere",
    selectRow: (label: string) => `Vælg ${label}`
  }
] as const;

export type BlazorCulture = (typeof blazorCultures)[number];

/**
 * The locales of the culture projects in blazor/tests/playwright.config.ts. Every project sets its locale explicitly:
 * headless Chromium in the container otherwise reports "en-US@posix", which the .NET WebAssembly runtime rejects.
 */
export const blazorLocales: string[] = blazorCultures.map((culture) => culture.locale);

/**
 * The locale of the culture project the running test belongs to, for browser contexts a test opens itself
 */
export function blazorLocale(): string {
  return blazorTexts().locale;
}

/**
 * The text map of the culture project the running test belongs to
 */
export function blazorTexts(): BlazorCulture {
  const locale = test.info().project.use.locale;
  const culture = blazorCultures.find((candidate) => candidate.locale === locale);
  if (!culture) throw new Error(`The project "${test.info().project.name}" has no Blazor culture; its locale is "${locale}".`);
  return culture;
}

/**
 * Messages the account API returns; the Blazor pages show them as returned, in English, in every culture
 */
export const accountApiMessages = {
  wrongCode: "The code is wrong or no longer valid.",
  tooManyAttempts: "Too many attempts, please request a new code.",
  codeNoLongerValid: "The code is no longer valid, please request a new code.",
  tooManyStarts: "Too many attempts to confirm this email address. Please try again later.",
  cannotChangeOwnUserRole: "You cannot change your own user role.",
  onlyOwnersCanChangeUserRoles: "Only owners are allowed to change the user roles of users.",
  userNotFound: (userId: string) => `User with id '${userId}' not found.`,
  userAlreadyExists: (email: string) => `The user '${email}' already exists.`,
  onlyOwnersCanInviteUsers: "Only owners are allowed to invite other users.",
  onlyOwnersCanDeleteUsers: "Only owners are allowed to delete other users.",
  cannotDeleteYourself: "You cannot delete yourself.",
  usersNotFound: (userIds: string[]) => `Users with ids '${userIds.join(", ")}' not found.`,
  deletedUserNotFound: (userId: string) => `Deleted user with id '${userId}' not found.`,
  deletedUsersNotFound: (userIds: string[]) => `Deleted users with ids '${userIds.join(", ")}' not found.`,
  onlyOwnersAndAdminsCanViewDeletedUsers: "Only owners and admins can view deleted users.",
  onlyOwnersAndAdminsCanRestoreUsers: "Only owners and admins can restore deleted users.",
  onlyOwnersAndAdminsCanPurgeUsers: "Only owners and admins can permanently delete users.",
  onlyOwnersCanBulkPurgeUsers: "Only owners can permanently delete users from the recycle bin.",
  onlyOwnersCanEmptyRecycleBin: "Only owners can empty the deleted users recycle bin.",
  noUserSelected: "At least one user must be selected for deletion.",
  tooManyUsersSelected: "Cannot delete more than 100 users at once."
} as const;
